### ISSUE TITLE
Unrecognizable Risk Assessing Fields

### ISSUE THREAD

**Issue by julesntare** [forestdatapartnership/whisp#19]
Hello @jonnvega,

Where can the fields determine the higher/lower risk of farms in the deforestation zone? that will be so helpful. Thank you

**Comment by andyarnell** [comment]
The risk fields are produced by the API now. Answering on behalf of @jonnvega who's is currently maintaining the API. 

To see the risk indicator column scroll all the way to the far right (there are many more columns produced currently for the benefit of a dashboard output we are working on., These will be tidied in due course).

Also note that this is an draft version of the risk indicator. Exact values and the decision tree will likely need testing and adjusting over time.

Let me know if this is what you mean and we can close the issue?

**Comment by julesntare** [comment]
Hello,

Yeah I truly understand you are still experimenting risk indicator fields.

I meant the disturbances fields aren't included in API fields response. What I can see is tree cover fields and agriculture fields.

Let me know if there are specific fields to help in risk assessment.

**Comment by andyarnell** [comment]
have you tried recently? 
They should be in there and are showing when i run it. 
May be try again using the below link and scroll all the way to the right of the table.
https://whisp.openforis.org/submit-geometry 
NB The Geo id version is down due to temporary issues on the asset registry side at AgStack, so the above link is for use with  geojson input (such as the example file).

**Comment by julesntare** [comment]
What I meant was not from CSV fields, but API json response fields. That is the part missing risk indicators fields. thanks

**Comment by andyarnell** [comment]
This is best addressed by @jonnvega.
